AllCops:
  NewCops: enable
  Exclude:
    - Guardfile
  SuggestExtensions: false
Metrics/AbcSize:
  Max: 25
Metrics/BlockLength:
  Max: 50
Layout/LineLength:
  Max: 250
Style/Documentation:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false